cursor #e5e1e9
cursor_text_color #c9c5d0

foreground            #e5e1e9
background            #141318
selection_foreground  #312e41
selection_background  #c9c3dc
url_color             #c8bfff
color0   #141318
color1   #e25143
color2   #6ed673
color3   #dbd77b
color4   #8670e7
color5   #9e98bf
color6   #c8bfff
color7   #abb2bf
color8   #5c6370
color9   #e0675f
color10   #86e08a
color11   #e8e597
color12   #d6ccff
color13   #736ece
color14   #836db8
color15   #ffffff
