$image = Null
$background = rgba(000000ff)

$image = Null
$error = rgba(ff3b3bff)

$image = Null
$error_container = rgba(330000ff)

$image = Null
$inverse_on_surface = rgba(f2f2f2ff)

$image = Null
$inverse_primary = rgba(aaaaaaff)

$image = Null
$inverse_surface = rgba(1a1a1aff)

$image = Null
$on_background = rgba(f5f5f5ff)

$image = Null
$on_error = rgba(ffffff)

$image = Null
$on_error_container = rgba(ffffff)

$image = Null
$on_primary = rgba(000000ff)

$image = Null
$on_primary_container = rgba(1a1a1aff)

$image = Null
$on_primary_fixed = rgba(0a0a0aff)

$image = Null
$on_primary_fixed_variant = rgba(141414ff)

$image = Null
$on_secondary = rgba(e0e0e0ff)

$image = Null
$on_secondary_container = rgba(121212ff)

$image = Null
$on_secondary_fixed = rgba(060606ff)

$image = Null
$on_secondary_fixed_variant = rgba(141414ff)

$image = Null
$on_surface = rgba(f0f0f0ff)

$image = Null
$on_surface_variant = rgba(b3b3b3ff)

$image = Null
$on_tertiary = rgba(dadadaff)

$image = Null
$on_tertiary_container = rgba(1a1a1aff)

$image = Null
$on_tertiary_fixed = rgba(000000ff)

$image = Null
$on_tertiary_fixed_variant = rgba(141414ff)

$image = Null
$outline = rgba(555555ff)

$image = Null
$outline_variant = rgba(2a2a2aff)

$image = Null
$primary = rgba(f5f5f5ff)

$image = Null
$primary_container = rgba(0a0a0aff)

$image = Null
$primary_fixed = rgba(ffffff)

$image = Null
$primary_fixed_dim = rgba(dcdcdcff)

$image = Null
$scrim = rgba(000000ff)

$image = Null
$secondary = rgba(bfbfbfff)

$image = Null
$secondary_container = rgba(1a1a1aff)

$image = Null
$secondary_fixed = rgba(e6e6e6ff)

$image = Null
$secondary_fixed_dim = rgba(bfbfbfff)

$image = Null
$shadow = rgba(000000ff)

$image = Null
$source_color = rgba(ffffffff)

$image = Null
$surface = rgba(000000ff)

$image = Null
$surface_bright = rgba(0f0f0fff)

$image = Null
$surface_container = rgba(121212ff)

$image = Null
$surface_container_high = rgba(1a1a1aff)

$image = Null
$surface_container_highest = rgba(262626ff)

$image = Null
$surface_container_low = rgba(0d0d0dff)

$image = Null
$surface_container_lowest = rgba(000000ff)

$image = Null
$surface_dim = rgba(000000ff)

$image = Null
$surface_tint = rgba(ffffff)

$image = Null
$surface_variant = rgba(2a2a2aff)

$image = Null
$tertiary = rgba(dcdcdcff)

$image = Null
$tertiary_container = rgba(1a1a1aff)

$image = Null
$tertiary_fixed = rgba(ebebebff)

$image = Null
$tertiary_fixed_dim = rgba(dcdcdcff)
