##########################################################################################
### LOOK AND FEEL ###
##########################################################################################

source = colors.conf

general {
    gaps_in = 5
    gaps_out = 6
    border_size = 0
    # Permite redimensionar arrastrando bordes o huecos
    resize_on_border = true

    # Evita tearing
    allow_tearing = false

    layout = dwindle
    col.active_border = $primary
    col.inactive_border = $surface
}

##########################################################################################
### DECORATION ###
##########################################################################################

decoration {
    rounding = 6
    rounding_power = 2

    # Opacidad
    active_opacity = 1
    inactive_opacity = 0.9

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = $shadow
    }

    blur {
        enabled = true
        size = 5
        passes = 2
        vibrancy = 0.17
    }
}

##########################################################################################
### ANIMATIONS ###
##########################################################################################

animations {
    enabled = yes

    # Curvas
    bezier = easeOutQuint, 0.23, 1, 0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear, 0, 0, 1, 1
    bezier = almostLinear, 0.5, 0.5, 0.75, 1
    bezier = quick, 0.15, 0, 0.1, 1
    bezier = overshoot, 0.05, 0.9, 0.1, 1.1

    # Animaciones
    animation = global, 1, 10, default
    animation = border, 1, 5.3, easeOutQuint
    animation = windows, 1, 4.8, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.5, linear, popin 87%
    animation = fadeIn, 1, 1.7, almostLinear
    animation = fadeOut, 1, 1.4, almostLinear
    animation = fade, 1, 3.0, quick
    animation = layers, 1, 3.8, easeOutQuint
    animation = layersIn, 1, 4, easeOutQuint, fade
    animation = layersOut, 1, 1.5, linear, fade
    animation = fadeLayersIn, 1, 1.7, almostLinear
    animation = fadeLayersOut, 1, 1.3, almostLinear
    animation = workspaces, 1, 5, easeOutQuint, slide
}

##########################################################################################
### DWINDLE & MASTER LAYOUT ###
##########################################################################################

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

##########################################################################################
### MISC ###
##########################################################################################

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
}
