##########################################################################################
#
#            ⋆｡°✩₊ °✦ ‧  ‧ ₊ ˚✧₊ °✦ HYPRLAND CONFIGURATION ⋆｡°✩₊ °✦ ‧  ‧ ₊ ˚✧₊ °✦ 
#
##########################################################################################

# Variables & Directories

$mainMod = SUPER
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$browser = zen-browser
$notes = obsidian

$scriptsDir = $HOME./config/hypr/scripts

source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/decor.conf

##########################################################################################
#
#     ⋆｡°✩₊ °✦ ‧  ‧ ₊ ˚✧₊ °✦ MONITORS, AUTOSTART & INPUTS   ⋆｡°✩₊ °✦ ‧  ‧ ₊ ˚✧₊ °✦ 
#
##########################################################################################

monitor = ,preferred,auto,1 

# exec-once = dms run
exec-once = waybar 
exec-once = waypaper --restore

#############################
### ENVIRONMENT VARIABLES ###
#############################


env = XCURSOR_SIZE,18
env = HYPRCURSOR_SIZE,18

#############
### INPUT ###
#############

input {
    kb_layout = latam
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    sensitivity = 0.3, # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat
    #force_no_accel = true
    follow_mouse = 1
  
    touchpad {
        natural_scroll = true
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


##########################################################################################
#
#     ⋆｡°✩₊ °✦ ‧  ‧ ₊ ˚✧₊ °✦ WINDOWS, WORKSPACES & LAYERRULES ⋆｡°✩₊ °✦ ‧  ‧ ₊ ˚✧₊ °✦ 
#
##########################################################################################

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Custom Transparency
# windowrulev2 = opacity <active>,<inactive>,class:<app_class>

windowrulev2 = opacity 0.6 0.7, class:Spotify
windowrulev2 = opacity 0.8 0.7, class:discord
windowrulev2 = opacity 0.6 0.6, class:obsidian
windowrulev2 = opacity 0.7 0.7, class:vesktop
windowrulev2 = opacity 0.8 0.7, class:thunar
windowrulev2 = opacity 0.8 0.7, class:org.kde.dolphin
windowrulev2 = opacity 0.8 0.7, class:Code
windowrulev2 = opacity 0.9 0.8, class:org.kde.kate
windowrulev2 = opacity 0.8 0.8, class:Thuna
windowrulev2 = opacity 0.8 0.8, class:org.telegram.desktop
windowrulev2 = opacity 0.8 0.8, class:kitty

layerrule = blur,waybar
layerrule = ignorealpha,waybar

layerrule = blur,wofi
layerrule = ignorealpha,wofi

layerrule = blur,wlogout
layerrule = ignorealpha,wlogout
