foreground #ffffff
background #000000
cursor #ffffff
cursor_text_color #000000

# ANSI black/white puros
color0  #000000
color8  #808080

color7  #ffffff
color15 #ffffff

# Los demás pueden ser grises
color1  #cccccc
color2  #cccccc
color3  #cccccc
color4  #cccccc
color5  #cccccc
color6  #cccccc

color9  #999999
color10 #999999
color11 #999999
color12 #999999
color13 #999999
color14 #999999

